/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ico.fes;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Silla s1= new Silla(4, "madera");
        System.out.println(s1);
    }
}
